### ISSUE TITLE
Linter ignores app:lint.xml file

### ISSUE THREAD

**Issue by w-j-francis** [bitrise-steplib/bitrise-step-android-lint#10]
Errors found:
  
  /bitrise/src/app: Error: Unknown issue id "StyleCycle", found in /bitrise/src/app/lint.xml [LintError]

This is what I keep receiving on Bitrise (not when I run locally). This issue is not in my app/lint.xml file so I guess maybe there is a default file being copied over which includes this invalid ID?

**Comment by fehersanyi-bitrise** [comment]
Hy @w-j-francis!

Could you please send me the url of this build, so I can check out the logs for some more details?

**Comment by w-j-francis** [comment]
@fehersanyi-bitrise https://app.bitrise.io/app/a01515c586cede55#/builds
I believe around build #40 i went ahead and turned off the linter so I could get my builds.

**Comment by fehersanyi-bitrise** [comment]
Hy @w-j-francis unfortunately I cant reach your builds like this 🙃 I will need a specific build url to see the logs.
