### ISSUE TITLE
No way to configure build.gradle location

### ISSUE THREAD

**Issue by Danm72** [bitrise-steplib/bitrise-step-android-lint#11]
We use the kotlin dsl for our gradle file so our build.gradle is actually build.gradle.kt 

It would be nice to be able to pass a param like:
        - build_gradle_path: "$PROJECT_LOCATION/$MODULE/build.gradle.kts"

**Comment by fehersanyi-bitrise** [comment]
Hy @Danm72 

Where can't you configure the path? this should be no problem as far as I know 🤔
this should be the Project location input if I'm right

**Comment by Danm72** [comment]
So the project location isn't the problem as far as I know, the project is still in the same location. The different is - the script is looking for src/build.gradle but the actual file is called build.gradle.kts and i can't configure it to look for that naming scheme

**Comment by fehersanyi-bitrise** [comment]
Could you please send us the url of this build please? and please enable support user on the settings tab, I would like to run a few test builds if it is okay with you.

**Comment by lpusok** [comment]
Hello @Danm72!
Created a ticket with the issue, passed it on to the team. Thanks for the report!

**Comment by okcoker** [comment]
Also having this problem. Any progress on this so far? 

Edit: I think this is moreso a problem with bitrise steps in general: https://github.com/bitrise-steplib/steps-project-scanner/issues/57

**Comment by fehersanyi-bitrise** [comment]
Hy @okcoker 

It is already in progress. I would say that it should be possible in a few days.
