### ISSUE TITLE
No build.gradle file found in (/bitrise/src) with build.gradle.kts

### ISSUE THREAD

**Issue by WhosNickDoglio** [bitrise-steplib/bitrise-step-android-lint#12]
With [Kotlin Gradle DSL](https://github.com/bitrise-steplib/steps-project-scanner/issues/57#issuecomment-471931519l) support recently added I was eager to try it.  

While scanning the project now works seamlessly the Android Lint Step now fails with the following error: Failed to open project, error: no build.gradle file found in (/bitrise/src)

**Comment by fehersanyi-bitrise** [comment]
Hello there, 

Could you pleases end us a build's url with this failure please, so we could check the full logs, and try to come up with a possible solution?

**Comment by WhosNickDoglio** [comment]
Yes of course!

[Build URL](https://app.bitrise.io/build/74adb52c5cbc7230?token=1j3zPdQ79QIiGHSoSSoUXg)

I've also downloaded and attached the [logs files.](https://github.com/bitrise-steplib/bitrise-step-android-lint/files/2961330/74adb52c5cbc7230.log)

**Comment by fehersanyi-bitrise** [comment]
Hy there!

gradle.kts is currently in the sprint so the steps will not necessary recognise them as I learned

**Comment by WhosNickDoglio** [comment]
Closing this now because it appears to be fixed! 👍
