### ISSUE TITLE
Lint cannot match 2 errors from Baseline

### ISSUE THREAD

**Issue by olegosipenko** [bitrise-steplib/bitrise-step-android-lint#16]
Recently we decided to enable Lint in our project. But as we have a lot of legacy code, we decided to use a baseline feature, to suppress existing errors and only run checks against new code. 
For that we created baselines, committed them to version control. But now we have builds failing because 2 of existing errors not matched with baseline.
When I run lint locally I see in logs:
```
> Task :app:lintDebug
Lint found no errors or warnings (49 errors, 252 warnings filtered by baseline app-lint-baseline.xml)
```
When the same is built on Bitrise we got:
```
Lint found 2 errors (47 errors, 252 warnings filtered by baseline app-lint-baseline.xml)

2 errors/warnings were listed in the baseline file (/bitrise/src/config/lint/app-lint-baseline.xml) but not found in the project; perhaps they have been fixed?
```
These 2 errors which fail the build are already in baseline, total number of errors is identical. Just 2 of them somehow not matched with baseline. When I try to recreate baseline again I got baseline identical to previous one.

Our [build url](https://app.bitrise.io/build/0946fb9e3a69cf56#?tab=log)

**Comment by mjones-droid** [comment]
Hey @olegosipenko! 

I'm sorry you're having issues. Would you mind [enabling support access](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) so we can take a closer look at everything?

**Comment by olegosipenko** [comment]
> Hey @olegosipenko!
> 
> I'm sorry you're having issues. Would you mind [enabling support access](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) so we can take a closer look at everything?

Enabled

**Comment by mjones-droid** [comment]
Hi @olegosipenko... 

Interesting. Just from looking at the log I'm not sure why this is happening. Can you try doing a clean clone locally and testing with the Bitrise CLI? More information can be found here:

https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/

https://discuss.bitrise.io/t/how-to-debug-your-build-locally-it-works-on-my-mac-pc-but-not-on-bitrise-io/392

Let me know if you encounter the same issues after going through these troubleshooting steps. 

Matthew
Senior Customer Engineer
