### ISSUE TITLE
Respect additional flags in every Gradle call

### ISSUE THREAD

**Issue by ofalvai** [bitrise-steplib/bitrise-step-android-lint#21]
### Troubleshooting

- [X] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? latest
- Is the issue reproducible with the latest version? YES
- Does the issue happen sporadically, or every time? EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? YES

### Useful information

- [FAQ](https://devcenter.bitrise.io/faq/faq-index/)
- [devcenter.bitrise.io](https://devcenter.bitrise.io/)

### Issue description

If someone needs to set additional Gradle flags to have a successful build, this step doesn't work, even when filling out the Gradle flags input. This is because the step executes Gradle multiple times, and the additional flags are only applied to the main Gradle call.

For example, the step executes `gradle tasks --all` to display and validate the available variants: https://github.com/bitrise-steplib/bitrise-step-android-lint/blob/master/main.go#L88

### Bitrise info

- Build URL: _Please share the build URL with us._
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: _YES / NO_
- Log: 

<details>
  <pre>
 
  </pre>
</details>

### Steps to reproduce

1. Set up a Gradle project that expects certain command line flags (or properties passed as flags)
2. Add this step
3. Specify the extra Gradle flags in the step input
4. Run

**Comment by daniel-shuy** [comment]
This requires updating [github.com/bitrise-io/go-android](https://github.com/bitrise-io/go-android), I've created a initial PR there (bitrise-io/go-android#45)

**Comment by ofalvai** [comment]
Hey @daniel-shuy are you planning to keep working on this or should we take it over from here?

**Comment by daniel-shuy** [comment]
@ofalvai yup sorry was caught up in other things, will still try to complete it

**Comment by daniel-shuy** [comment]
Created a PR (#25)
