### ISSUE TITLE
Name of output artifact of module which in subfolder of root project

### ISSUE THREAD

**Issue by LinkLu-iherb** [bitrise-steplib/bitrise-step-android-lint#24]
We are trying using bitrise-step-android-lint to integrate lint with bitrise.

And found that the artifact name output the subfolder name instead of the android module name itself.

eg: project structure:
- root proj
  - moduleInRoot
  - subfolder
    - moduleA
    - moduleB

output artifact name:  moduleInRoot-time.ext, subfolder-time.ext, subfolder-time.ext

With checking out the source code, found related code lines:

https://github.com/bitrise-steplib/bitrise-step-android-lint/blob/27d088e3d4e085ab7d4348c766cb08bd88fa567d/main.go#L32

and 

https://github.com/bitrise-io/go-android/blob/85247bb2c5c67571c3529e3206af515bab5bc853/gradle/project.go#L136

it seems hardcoded first segment of relative path of root project as artifact name.

Any idea?

**Comment by ofalvai** [comment]
Hey @LinkLu-iherb, what is the exact issue this naming pattern causes you? Is the lint report not exported as a build artifact?

It would help us a lot if you could enable support access on your app and share a build URL so that we can take a look at the exact build logs and artifacts.

**Comment by LinkLu-iherb** [comment]
Well, we have multiple modules in our project, some placed in the directory of root project, eg:"moduleInRoot", some are not, eg:
we have a folder named "foundation" in root project and several modules in it, let's say "moduleA", and "moduleB":

what we expect: 
output lint reports with naming like:
moduleInRoot-lint-results-debug.html,foundation-moduleA-lint-results-debug.html,foundation-moduleB-lint-results-debug.html
or
moduleInRoot-lint-results-debug.html, moduleA-lint-results-debug.html, moduleB-lint-results-debug.html

what we got actually:
moduleInRoot-lint-results-debug.html, foundation-lint-results-debug.html, foundation-lint-results-debug-(time).html
