### ISSUE TITLE
Invalid fetching variants error output color on configuration error

### ISSUE THREAD

**Issue by koral--** [bitrise-steplib/bitrise-step-android-lint#7]
Red color embraces only 1st line, despite that error message is far away.
![image](https://user-images.githubusercontent.com/3340954/46839970-f43f3c80-cdc0-11e8-824d-6b2309c671f5.png)

Build URL: https://app.bitrise.io/build/c5751c6607d82a81
Repo URL: https://github.com/DroidsOnRoids/TracepathAndroid/

**Comment by godrei** [comment]
Hi @koral-- ,
sorry for my late response, does this issue still exist?

**Comment by koral--** [comment]
It seems to be fixed in the meantime :)
